// Generated by tools/native-apps/build.mjs. Edit the native app package instead.
import { styled } from '@linaria/react';
import { t } from '@lingui/core/macro';
import { useState } from 'react';
import { isDefined } from 'twenty-shared/utils';
import { LightIconButton } from 'twenty-ui/components';
import { IconList, IconX, useIcons } from 'twenty-ui/icon';
import { Button } from 'twenty-ui/primitives/input';
import { Dialog } from 'twenty-ui/primitives/surfaces';
import { themeCssVariables } from 'twenty-ui/theme';

import { useSnackBar } from '@/app/native-extension-host/api/modules/ui/feedback/snack-bar-manager/hooks/useSnackBar';
import { useRecordLists } from '../hooks/useRecordLists';
import { useRemoveRecordsFromListBySourceRecordIds } from '../hooks/useRemoveRecordsFromListBySourceRecordIds';

const StyledHeader = styled.div`
  align-items: center;
  display: flex;
  justify-content: space-between;
  width: 100%;
`;

const StyledContent = styled.div`
  display: flex;
  flex-direction: column;
  gap: ${themeCssVariables.spacing[3]};
`;

const StyledDescription = styled.div`
  color: ${themeCssVariables.font.color.secondary};
  font-size: ${themeCssVariables.font.size.sm};
`;

const StyledListButton = styled.button<{ selected: boolean }>`
  align-items: center;
  background: ${({ selected }) =>
    selected
      ? themeCssVariables.background.transparent.blue
      : themeCssVariables.background.secondary};
  border: 1px solid
    ${({ selected }) =>
      selected
        ? themeCssVariables.color.blue
        : themeCssVariables.border.color.medium};
  border-radius: ${themeCssVariables.border.radius.md};
  color: ${themeCssVariables.font.color.primary};
  cursor: pointer;
  display: flex;
  font-family: ${themeCssVariables.font.family};
  font-size: ${themeCssVariables.font.size.md};
  gap: ${themeCssVariables.spacing[2]};
  min-height: 40px;
  padding: ${themeCssVariables.spacing[2]} ${themeCssVariables.spacing[3]};
  text-align: left;

  &:focus-visible {
    outline: 2px solid ${themeCssVariables.color.blue};
    outline-offset: 2px;
  }
`;

const StyledInput = styled.input`
  background: ${themeCssVariables.background.primary};
  border: 1px solid ${themeCssVariables.border.color.medium};
  border-radius: ${themeCssVariables.border.radius.md};
  color: ${themeCssVariables.font.color.primary};
  font-family: ${themeCssVariables.font.family};
  font-size: ${themeCssVariables.font.size.md};
  min-height: 40px;
  padding: 0 ${themeCssVariables.spacing[3]};

  &:focus {
    border-color: ${themeCssVariables.color.blue};
    outline: none;
  }
`;

type BulkRemoveRecordsFromListModalProps = {
  objectMetadataId: string;
  recordIds: string[];
  onClose: () => void;
};

export const BulkRemoveRecordsFromListModal = ({
  objectMetadataId,
  recordIds,
  onClose,
}: BulkRemoveRecordsFromListModalProps) => {
  const [selectedRecordListId, setSelectedRecordListId] = useState('');
  const [searchQuery, setSearchQuery] = useState('');
  const { recordLists, loading: areRecordListsLoading } = useRecordLists();
  const { removeRecordsFromList, loading: isRemoving } =
    useRemoveRecordsFromListBySourceRecordIds();
  const { enqueueErrorSnackBar, enqueueSuccessSnackBar } = useSnackBar();
  const { getIcon } = useIcons();

  const matchingRecordLists = recordLists.filter(
    (recordList) => recordList.parentObjectMetadataId === objectMetadataId,
  );
  const filteredRecordLists = matchingRecordLists.filter((recordList) =>
    recordList.name
      .toLocaleLowerCase()
      .includes(searchQuery.trim().toLocaleLowerCase()),
  );

  const handleSubmit = async () => {
    try {
      const result = await removeRecordsFromList({
        recordListId: selectedRecordListId,
        sourceRecordIds: recordIds,
        parentObjectMetadataId: objectMetadataId,
      });

      if (!isDefined(result)) {
        throw new Error('Bulk list removal did not return a result');
      }

      enqueueSuccessSnackBar({
        message:
          result.skippedCount > 0
            ? t`${result.removedCount} records removed; ${result.skippedCount} were not in the list`
            : t`${result.removedCount} records removed from list`,
      });
      onClose();
    } catch {
      enqueueErrorSnackBar({
        message: t`Failed to remove records from list`,
      });
    }
  };

  return (
    <Dialog.Root open onOpenChange={(open) => !open && onClose()}>
      <Dialog.Popup
        aria-label={t`Remove from list`}
        container={document.body}
        size="md"
      >
        <Dialog.Header>
          <StyledHeader>
            <span>{t`Remove from list`}</span>
            <LightIconButton aria-label={t`Close`} size="sm" onClick={onClose}>
              <IconX />
            </LightIconButton>
          </StyledHeader>
        </Dialog.Header>
        <Dialog.Body>
          <StyledContent>
            <StyledDescription>
              {t`Remove ${recordIds.length} selected records from a list.`}
            </StyledDescription>
            <StyledInput
              aria-label={t`Search lists`}
              value={searchQuery}
              placeholder={t`Search lists...`}
              onChange={(event) => setSearchQuery(event.target.value)}
            />
            {filteredRecordLists.map((recordList) => {
              const RecordListIcon = isDefined(recordList.icon)
                ? getIcon(recordList.icon)
                : IconList;

              return (
                <StyledListButton
                  key={recordList.id}
                  type="button"
                  selected={selectedRecordListId === recordList.id}
                  aria-pressed={selectedRecordListId === recordList.id}
                  onClick={() => setSelectedRecordListId(recordList.id)}
                >
                  <RecordListIcon size={16} />
                  {recordList.name}
                </StyledListButton>
              );
            })}
            {!areRecordListsLoading && matchingRecordLists.length === 0 && (
              <StyledDescription>{t`No lists available yet.`}</StyledDescription>
            )}
            {!areRecordListsLoading &&
              matchingRecordLists.length > 0 &&
              filteredRecordLists.length === 0 && (
                <StyledDescription>
                  {t`No lists match your search.`}
                </StyledDescription>
              )}
          </StyledContent>
        </Dialog.Body>
        <Dialog.Footer>
          <Button variant="outline" onClick={onClose}>
            {t`Cancel`}
          </Button>
          <Button
            color="accent"
            variant="solid"
            disabled={
              selectedRecordListId.length === 0 || areRecordListsLoading
            }
            loading={isRemoving}
            onClick={() => void handleSubmit()}
          >
            {t`Remove from list`}
          </Button>
        </Dialog.Footer>
      </Dialog.Popup>
    </Dialog.Root>
  );
};
