// Generated by tools/native-apps/build.mjs. Edit the native app package instead.
import { styled } from '@linaria/react';
import { t } from '@lingui/core/macro';
import { useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { isDefined } from 'twenty-shared/utils';
import { Button } from 'twenty-ui/primitives/input';
import { LightIconButton } from 'twenty-ui/components';
import {
  IconChevronDown,
  IconChevronUp,
  IconCheck,
  IconExternalLink,
  IconList,
  IconTrash,
  useIcons,
} from 'twenty-ui/icon';
import { themeCssVariables } from 'twenty-ui/theme';

import { useFilteredObjectMetadataItems } from '@/app/native-extension-host/api/modules/object-metadata/hooks/useFilteredObjectMetadataItems';
import { type FieldMetadataItem } from '@/app/native-extension-host/api/modules/object-metadata/types/FieldMetadataItem';
import { useFindOneRecord } from '@/app/native-extension-host/api/modules/object-record/hooks/useFindOneRecord';
import { useRefetchFindManyRecords } from '@/app/native-extension-host/api/modules/object-record/hooks/useRefetchFindManyRecords';
import { useUpdateOneRecord } from '@/app/native-extension-host/api/modules/object-record/hooks/useUpdateOneRecord';
import { type ObjectRecord } from '@/app/native-extension-host/api/modules/object-record/types/ObjectRecord';
import { useSnackBar } from '@/app/native-extension-host/api/modules/ui/feedback/snack-bar-manager/hooks/useSnackBar';
import { useRecordListMemberships } from '../hooks/useRecordListMemberships';
import { useRecordLists } from '../hooks/useRecordLists';
import { type RecordListMembership } from '../types/RecordList';
import { getRecordListPath } from '../utils/getRecordListPath';
import { FieldMetadataType } from '@/app/native-extension-host/api/generated-metadata/graphql';

const StyledSection = styled.section`
  border-top: 1px solid ${themeCssVariables.border.color.light};
  display: flex;
  flex-direction: column;
  gap: ${themeCssVariables.spacing[3]};
  padding: ${themeCssVariables.spacing[4]};
`;

const StyledHeader = styled.div`
  align-items: center;
  display: flex;
  justify-content: space-between;
`;

const StyledMembershipPicker = styled.div`
  position: relative;
`;

const StyledMembershipTrigger = styled.button`
  align-items: center;
  background: transparent;
  border: 1px solid ${themeCssVariables.border.color.medium};
  border-radius: ${themeCssVariables.border.radius.md};
  color: ${themeCssVariables.font.color.primary};
  cursor: pointer;
  display: flex;
  font: inherit;
  justify-content: space-between;
  min-height: 36px;
  padding: 0 ${themeCssVariables.spacing[2]};
  text-align: left;
  width: 100%;

  &:hover,
  &:focus-visible {
    background: ${themeCssVariables.background.transparent.light};
    outline: 1px solid ${themeCssVariables.border.color.medium};
  }
`;

const StyledMembershipValues = styled.span`
  color: ${themeCssVariables.font.color.secondary};
  overflow: hidden;
  text-overflow: ellipsis;
  white-space: nowrap;
`;

const StyledListPicker = styled.div`
  background: ${themeCssVariables.background.primary};
  border: 1px solid ${themeCssVariables.border.color.medium};
  border-radius: ${themeCssVariables.border.radius.md};
  box-shadow: ${themeCssVariables.boxShadow.strong};
  display: flex;
  flex-direction: column;
  left: 0;
  max-height: 240px;
  overflow-y: auto;
  position: absolute;
  right: 0;
  top: calc(100% + ${themeCssVariables.spacing[1]});
  z-index: 2;
`;

const StyledListOption = styled.button<{ selected: boolean }>`
  align-items: center;
  background: ${({ selected }) =>
    selected ? themeCssVariables.background.transparent.light : 'transparent'};
  border: 0;
  color: ${themeCssVariables.font.color.primary};
  cursor: pointer;
  display: flex;
  font: inherit;
  gap: ${themeCssVariables.spacing[2]};
  min-height: 36px;
  padding: ${themeCssVariables.spacing[1]} ${themeCssVariables.spacing[2]};
  text-align: left;

  &:hover,
  &:focus-visible {
    background: ${themeCssVariables.background.transparent.light};
    outline: none;
  }
`;

const StyledOptionCheck = styled.span`
  align-items: center;
  display: flex;
  height: 16px;
  justify-content: center;
  width: 16px;
`;

const StyledTitle = styled.div`
  align-items: center;
  color: ${themeCssVariables.font.color.primary};
  display: flex;
  font-size: ${themeCssVariables.font.size.md};
  font-weight: ${themeCssVariables.font.weight.medium};
  gap: ${themeCssVariables.spacing[1]};
`;

const StyledCards = styled.div`
  display: flex;
  flex-direction: column;
  gap: ${themeCssVariables.spacing[3]};
`;

const StyledCard = styled.div`
  border: 1px solid ${themeCssVariables.border.color.medium};
  border-radius: ${themeCssVariables.border.radius.lg};
  display: flex;
  flex-direction: column;
  gap: ${themeCssVariables.spacing[3]};
  padding: ${themeCssVariables.spacing[4]};
`;

const StyledCardHeader = styled.div`
  align-items: center;
  display: flex;
  gap: ${themeCssVariables.spacing[2]};
`;

const StyledListLink = styled.a`
  color: ${themeCssVariables.font.color.primary};
  flex: 1;
  font-size: ${themeCssVariables.font.size.md};
  font-weight: ${themeCssVariables.font.weight.medium};
  text-decoration: none;

  &:hover {
    text-decoration: underline;
  }
`;

const StyledFields = styled.div`
  display: flex;
  flex-direction: column;
  gap: ${themeCssVariables.spacing[1]};
`;

const StyledFieldRow = styled.div`
  align-items: center;
  display: grid;
  gap: ${themeCssVariables.spacing[3]};
  grid-template-columns: minmax(120px, 1fr) minmax(180px, 2fr);
  min-height: 32px;

  @media (max-width: 600px) {
    align-items: stretch;
    gap: ${themeCssVariables.spacing[1]};
    grid-template-columns: 1fr;
  }
`;

const StyledFieldLabel = styled.div`
  align-items: center;
  color: ${themeCssVariables.font.color.secondary};
  display: flex;
  gap: ${themeCssVariables.spacing[2]};
  min-width: 0;
`;

const StyledInput = styled.input`
  background: transparent;
  border: 0;
  border-radius: ${themeCssVariables.border.radius.sm};
  color: ${themeCssVariables.font.color.primary};
  font-family: ${themeCssVariables.font.family};
  font-size: ${themeCssVariables.font.size.md};
  min-height: 32px;
  min-width: 0;
  padding: 0 ${themeCssVariables.spacing[2]};
  width: 100%;

  &::placeholder {
    color: ${themeCssVariables.font.color.tertiary};
  }

  &:hover,
  &:focus-visible {
    background: ${themeCssVariables.background.transparent.light};
    outline: 1px solid ${themeCssVariables.border.color.medium};
  }
`;

const StyledSelect = styled.select`
  background: transparent;
  border: 0;
  border-radius: ${themeCssVariables.border.radius.sm};
  color: ${themeCssVariables.font.color.primary};
  font-family: ${themeCssVariables.font.family};
  font-size: ${themeCssVariables.font.size.md};
  min-height: 32px;
  min-width: 0;
  padding: 0 ${themeCssVariables.spacing[2]};
  width: 100%;

  &:hover,
  &:focus-visible {
    background: ${themeCssVariables.background.transparent.light};
    outline: 1px solid ${themeCssVariables.border.color.medium};
  }
`;

const StyledCheckbox = styled.input`
  height: 16px;
  margin-left: ${themeCssVariables.spacing[2]};
  width: 16px;
`;

const StyledShowFieldsButton = styled.button`
  align-items: center;
  align-self: flex-start;
  background: transparent;
  border: 0;
  border-radius: ${themeCssVariables.border.radius.sm};
  color: ${themeCssVariables.font.color.primary};
  cursor: pointer;
  display: flex;
  gap: ${themeCssVariables.spacing[1]};
  min-height: 28px;
  padding: 0;

  &:hover,
  &:focus-visible {
    color: ${themeCssVariables.font.color.secondary};
    outline: none;
  }
`;

const StyledEmptyState = styled.div`
  color: ${themeCssVariables.font.color.tertiary};
  padding: ${themeCssVariables.spacing[2]} 0;
`;

const COLLAPSED_MEMBERSHIP_COUNT = 3;
const COLLAPSED_FIELD_COUNT = 3;

export const RecordListMembershipsSection = ({
  sourceRecordId,
  parentObjectMetadataId,
}: {
  sourceRecordId: string;
  parentObjectMetadataId: string;
}) => {
  const [showAll, setShowAll] = useState(false);
  const [isPickerOpen, setIsPickerOpen] = useState(false);
  const { recordLists } = useRecordLists();
  const { memberships, addToList, removeFromList, isAdding, isRemoving } =
    useRecordListMemberships({
      sourceRecordId,
      parentObjectMetadataId,
    });
  const { enqueueErrorSnackBar } = useSnackBar();
  const compatibleLists = recordLists.filter(
    (recordList) =>
      recordList.parentObjectMetadataId === parentObjectMetadataId,
  );
  const membershipsByListId = new Map(
    memberships.map((membership) => [membership.recordList.id, membership]),
  );
  const visibleMemberships = showAll
    ? memberships
    : memberships.slice(0, COLLAPSED_MEMBERSHIP_COUNT);
  const { getIcon } = useIcons();

  return (
    <StyledSection aria-label={t`Lists`}>
      <StyledHeader>
        <StyledTitle>{t`Lists`}</StyledTitle>
      </StyledHeader>
      <StyledMembershipPicker>
        <StyledMembershipTrigger
          type="button"
          aria-label={t`Manage lists`}
          aria-expanded={isPickerOpen}
          onClick={() => setIsPickerOpen((isOpen) => !isOpen)}
        >
          <StyledMembershipValues>
            {memberships.length > 0
              ? memberships.map(({ recordList }) => recordList.name).join(', ')
              : t`Add to lists...`}
          </StyledMembershipValues>
          {isPickerOpen ? (
            <IconChevronUp size={16} />
          ) : (
            <IconChevronDown size={16} />
          )}
        </StyledMembershipTrigger>
        {isPickerOpen && (
          <StyledListPicker>
            {compatibleLists.map((recordList) => {
              const membership = membershipsByListId.get(recordList.id);
              const isSelected = isDefined(membership);

              return (
                <StyledListOption
                  key={recordList.id}
                  type="button"
                  selected={isSelected}
                  aria-pressed={isSelected}
                  disabled={isAdding || isRemoving}
                  onClick={async () => {
                    try {
                      if (isDefined(membership)) {
                        await removeFromList(recordList.id, membership.id);
                      } else {
                        await addToList(recordList.id);
                      }
                    } catch {
                      enqueueErrorSnackBar({
                        message: t`Failed to update list membership`,
                      });
                    }
                  }}
                >
                  <StyledOptionCheck>
                    {isSelected && <IconCheck size={16} />}
                  </StyledOptionCheck>
                  {recordList.name}
                </StyledListOption>
              );
            })}
            {compatibleLists.length === 0 && (
              <StyledEmptyState>{t`No lists available`}</StyledEmptyState>
            )}
          </StyledListPicker>
        )}
      </StyledMembershipPicker>
      <StyledCards>
        {visibleMemberships.map((membership) => (
          <RecordListMembershipCard
            key={membership.id}
            membership={membership}
            disabled={isRemoving}
            onRemove={async () => {
              await removeFromList(membership.recordList.id, membership.id);
            }}
          />
        ))}
      </StyledCards>
      {memberships.length > COLLAPSED_MEMBERSHIP_COUNT && (
        <Button
          variant="outline"
          size="sm"
          onClick={() => setShowAll((isShowingAll) => !isShowingAll)}
        >
          {showAll ? t`Show less` : t`Show more`}
        </Button>
      )}
    </StyledSection>
  );
};

const RecordListMembershipCard = ({
  membership,
  disabled,
  onRemove,
}: {
  membership: RecordListMembership;
  disabled: boolean;
  onRemove: () => Promise<void>;
}) => {
  const [showAllFields, setShowAllFields] = useState(false);
  const navigate = useNavigate();
  const { findObjectMetadataItemById } = useFilteredObjectMetadataItems();
  const entryObjectMetadataItem = findObjectMetadataItemById(
    membership.recordList.entryObjectMetadataId,
  );
  const { refetchFindManyRecords } = useRefetchFindManyRecords({
    objectMetadataNamePlural: entryObjectMetadataItem?.namePlural ?? '',
    includeAggregateQueries: true,
  });
  const editableFields =
    entryObjectMetadataItem?.fields.filter(
      (field) =>
        !field.isSystem &&
        field.name !== 'sourceRecord' &&
        field.type !== FieldMetadataType.RELATION &&
        field.type !== FieldMetadataType.MORPH_RELATION,
    ) ?? [];
  const visibleFields = showAllFields
    ? editableFields
    : editableFields.slice(0, COLLAPSED_FIELD_COUNT);
  const { getIcon } = useIcons();
  const ListIcon = isDefined(membership.recordList.icon)
    ? getIcon(membership.recordList.icon)
    : IconList;

  if (!isDefined(entryObjectMetadataItem)) {
    return null;
  }

  return (
    <StyledCard>
      <StyledCardHeader>
        <ListIcon size={18} />
        <StyledListLink href={getRecordListPath(membership.recordList.id)}>
          {membership.recordList.name}
        </StyledListLink>
        <LightIconButton
          aria-label={t`Open list`}
          size="sm"
          onClick={() => navigate(getRecordListPath(membership.recordList.id))}
        >
          <IconExternalLink />
        </LightIconButton>
        <LightIconButton
          aria-label={t`Remove from list`}
          size="sm"
          disabled={disabled}
          onClick={async () => {
            await onRemove();
            await refetchFindManyRecords();
          }}
        >
          <IconTrash />
        </LightIconButton>
      </StyledCardHeader>
      <RecordListMembershipFields
        membership={membership}
        entryObjectMetadataItem={entryObjectMetadataItem}
        fields={visibleFields}
      />
      {editableFields.length > COLLAPSED_FIELD_COUNT && (
        <StyledShowFieldsButton
          type="button"
          onClick={() => setShowAllFields((isShowingAll) => !isShowingAll)}
        >
          {showAllFields ? t`Show less` : t`Show more`}
        </StyledShowFieldsButton>
      )}
    </StyledCard>
  );
};

const RecordListMembershipFields = ({
  membership,
  entryObjectMetadataItem,
  fields,
}: {
  membership: RecordListMembership;
  entryObjectMetadataItem: NonNullable<
    ReturnType<
      ReturnType<
        typeof useFilteredObjectMetadataItems
      >['findObjectMetadataItemById']
    >
  >;
  fields: FieldMetadataItem[];
}) => {
  const { record, refetch } = useFindOneRecord<ObjectRecord>({
    objectNameSingular: entryObjectMetadataItem.nameSingular,
    objectRecordId: membership.id,
  });
  const { updateOneRecord } = useUpdateOneRecord();
  const { refetchFindManyRecords } = useRefetchFindManyRecords({
    objectMetadataNamePlural: entryObjectMetadataItem.namePlural,
  });

  const handleUpdate = async (fieldName: string, value: unknown) => {
    await updateOneRecord({
      objectNameSingular: entryObjectMetadataItem.nameSingular,
      idToUpdate: membership.id,
      updateOneRecordInput: { [fieldName]: value },
    });
    await Promise.all([refetch(), refetchFindManyRecords()]);
  };

  if (fields.length === 0) {
    return <StyledEmptyState>{t`No list fields`}</StyledEmptyState>;
  }

  return (
    <StyledFields>
      {fields.map((field) => (
        <RecordListMembershipField
          key={field.id}
          field={field}
          value={
            record?.[field.name] ?? membership.values?.[field.name] ?? null
          }
          onUpdate={(value) => handleUpdate(field.name, value)}
        />
      ))}
    </StyledFields>
  );
};

const RecordListMembershipField = ({
  field,
  value,
  onUpdate,
}: {
  field: FieldMetadataItem;
  value: unknown;
  onUpdate: (value: unknown) => Promise<void>;
}) => {
  const [draftValue, setDraftValue] = useState('');
  const { getIcon } = useIcons();
  const FieldIcon = isDefined(field.icon) ? getIcon(field.icon) : IconList;
  const stringValue =
    typeof value === 'string' || typeof value === 'number' ? String(value) : '';

  const persistDraftValue = () => {
    if (draftValue.length === 0 || draftValue === stringValue) {
      setDraftValue('');
      return;
    }

    const nextValue =
      field.type === FieldMetadataType.NUMBER ? Number(draftValue) : draftValue;

    void onUpdate(nextValue);
    setDraftValue('');
  };

  const inputValue = draftValue.length > 0 ? draftValue : stringValue;

  return (
    <StyledFieldRow>
      <StyledFieldLabel>
        <FieldIcon size={16} />
        {field.label}
      </StyledFieldLabel>
      {field.type === FieldMetadataType.SELECT && isDefined(field.options) ? (
        <StyledSelect
          aria-label={field.label}
          value={stringValue}
          onChange={(event) => void onUpdate(event.target.value || null)}
        >
          <option value="">{t`Set a value...`}</option>
          {field.options.map((option) => (
            <option key={option.id} value={option.value}>
              {option.label}
            </option>
          ))}
        </StyledSelect>
      ) : field.type === FieldMetadataType.BOOLEAN ? (
        <StyledCheckbox
          aria-label={field.label}
          type="checkbox"
          checked={value === true}
          onChange={(event) => void onUpdate(event.target.checked)}
        />
      ) : (
        <StyledInput
          aria-label={field.label}
          type={
            field.type === FieldMetadataType.NUMBER
              ? 'number'
              : field.type === FieldMetadataType.DATE
                ? 'date'
                : field.type === FieldMetadataType.DATE_TIME
                  ? 'datetime-local'
                  : 'text'
          }
          value={inputValue}
          placeholder={t`Set ${field.label}...`}
          onChange={(event) => setDraftValue(event.target.value)}
          onBlur={persistDraftValue}
          onKeyDown={(event) => {
            if (event.key === 'Enter') {
              persistDraftValue();
            }
          }}
        />
      )}
    </StyledFieldRow>
  );
};
