// Generated by tools/native-apps/build.mjs. Edit the native app package instead.
import { styled } from '@linaria/react';
import { t } from '@lingui/core/macro';
import { Dropdown } from 'twenty-ui/components';
import {
  IconChevronDown,
  IconFileExport,
  IconFileImport,
} from 'twenty-ui/icon';
import { themeCssVariables } from 'twenty-ui/theme';

import { useRecordIndexFileExport } from '@/app/native-extension-host/api/modules/object-record/record-index/hooks/useRecordIndexFileExport';

const StyledTriggerButton = styled.button`
  align-items: center;
  background: ${themeCssVariables.background.primary};
  border: 1px solid ${themeCssVariables.border.color.medium};
  border-radius: ${themeCssVariables.border.radius.md};
  color: ${themeCssVariables.font.color.primary};
  cursor: pointer;
  display: inline-flex;
  font-family: ${themeCssVariables.font.family};
  font-size: ${themeCssVariables.font.size.sm};
  gap: ${themeCssVariables.spacing[2]};
  min-height: 32px;
  padding: 0 ${themeCssVariables.spacing[2]};

  &:hover {
    background: ${themeCssVariables.background.transparent.light};
  }

  &:focus-visible {
    outline: 2px solid ${themeCssVariables.color.blue};
    outline-offset: 2px;
  }
`;

type RecordListImportExportDropdownProps = {
  filename: string;
  canImportCsv: boolean;
  onImportCsv: () => void;
};

export const RecordListImportExportDropdown = ({
  filename,
  canImportCsv,
  onImportCsv,
}: RecordListImportExportDropdownProps) => {
  const { download: downloadCsv } = useRecordIndexFileExport({
    filename: `${filename}.csv`,
    format: 'csv',
  });
  const { download: downloadExcel } = useRecordIndexFileExport({
    filename: `${filename}.xlsx`,
    format: 'xlsx',
  });

  return (
    <Dropdown.Root type="menu">
      <Dropdown.Trigger render={<StyledTriggerButton type="button" />}>
        <>
          <IconFileImport size={16} />
          {t`Import / Export`}
          <IconChevronDown size={16} />
        </>
      </Dropdown.Trigger>
      <Dropdown.Content aria-label={t`Import / Export`} width={250}>
        <Dropdown.Page id="root">
          {canImportCsv && (
            <Dropdown.ActionItem
              startIcon={<IconFileImport />}
              onClick={onImportCsv}
            >
              {t`Import CSV`}
            </Dropdown.ActionItem>
          )}
          <Dropdown.ActionItem
            startIcon={<IconFileExport />}
            onClick={() => void downloadCsv()}
          >
            {t`Export view as CSV`}
          </Dropdown.ActionItem>
          <Dropdown.ActionItem
            startIcon={<IconFileExport />}
            onClick={() => void downloadExcel()}
          >
            {t`Export view as Excel`}
          </Dropdown.ActionItem>
        </Dropdown.Page>
      </Dropdown.Content>
    </Dropdown.Root>
  );
};
