// Generated by tools/native-apps/build.mjs. Edit the native app package instead.
import { Type } from 'class-transformer';
import {
  ArrayMaxSize,
  IsArray,
  IsIn,
  IsNotEmpty,
  IsOptional,
  IsString,
  Matches,
  MaxLength,
  ValidateNested,
} from 'class-validator';
import { Field, InputType } from '@nestjs/graphql';

import { FieldMetadataType } from 'twenty-shared/types';

@InputType()
export class CreateRecordListTemplateFieldOptionInput {
  @IsString()
  @IsNotEmpty()
  @MaxLength(100)
  @Field()
  label: string;

  @IsString()
  @IsNotEmpty()
  @MaxLength(100)
  @Field()
  value: string;

  @IsString()
  @IsNotEmpty()
  @Field()
  color: string;
}

@InputType()
export class CreateRecordListTemplateFieldInput {
  @IsString()
  @Matches(/^[a-z][a-zA-Z0-9]*$/)
  @Field()
  name: string;

  @IsString()
  @IsNotEmpty()
  @MaxLength(100)
  @Field()
  label: string;

  @IsString()
  @IsIn([
    FieldMetadataType.TEXT,
    FieldMetadataType.NUMBER,
    FieldMetadataType.DATE,
    FieldMetadataType.BOOLEAN,
    FieldMetadataType.SELECT,
  ])
  @Field()
  type: string;

  @IsOptional()
  @IsString()
  @Field(() => String, { nullable: true })
  icon?: string | null;

  @IsOptional()
  @IsArray()
  @ArrayMaxSize(30)
  @ValidateNested({ each: true })
  @Type(() => CreateRecordListTemplateFieldOptionInput)
  @Field(() => [CreateRecordListTemplateFieldOptionInput], { nullable: true })
  options?: CreateRecordListTemplateFieldOptionInput[] | null;
}
