// Generated by tools/native-apps/build.mjs. Edit the native app package instead.
import { Field, InputType } from '@nestjs/graphql';
import { IsUUID } from 'class-validator';
import { GraphQLJSON } from 'graphql-type-json';

import { UUIDScalarType } from 'src/engine/core-modules/application/native-extension-host/api/engine/api/graphql/workspace-schema-builder/graphql-types/scalars';

@InputType()
export class UpdateRecordListEntryFieldsInput {
  @IsUUID()
  @Field(() => UUIDScalarType)
  entryObjectMetadataId: string;

  @IsUUID()
  @Field(() => UUIDScalarType)
  entryId: string;

  @Field(() => GraphQLJSON)
  data: Record<string, unknown>;
}
