// Generated by tools/native-apps/build.mjs. Edit the native app package instead.
import { HostSampleModule as NativeModule0 } from './5f1d0c2e-9a44-4a3b-8f2f-6a1b2c3d4e5f/server/host-sample.module';
import { RecordListModule as NativeModule1 } from './ac8f2b7a-15d3-47fa-a06c-2bfc6d85ec72/server/record-list.module';
export const NATIVE_APP_MODULES = [NativeModule0,NativeModule1];
