import {
  existsSync,
  mkdirSync,
  readFileSync,
  readdirSync,
  writeFileSync,
} from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import semver from 'semver';

export const root = path.resolve(
  path.dirname(fileURLToPath(import.meta.url)),
  '../..',
);
const walk = (directory) =>
  readdirSync(directory, { withFileTypes: true }).flatMap((entry) =>
    entry.isDirectory()
      ? walk(path.join(directory, entry.name))
      : [path.join(directory, entry.name)],
  );
const write = (file, content) => {
  mkdirSync(path.dirname(file), { recursive: true });
  if (!existsSync(file) || readFileSync(file, 'utf8') !== content)
    writeFileSync(file, content);
};
const header =
  '// Generated by tools/native-apps/build.mjs. Edit the native app package instead.\n';
const configuration = JSON.parse(
  readFileSync(path.join(root, 'native-apps.json'), 'utf8'),
);
// The host capability contract is owned by the server, so the build reads it
// from its source of truth instead of keeping a second copy of the range.
const capabilityUtilSource = readFileSync(
  path.join(
    root,
    'packages/twenty-server/src/engine/core-modules/application/native-extension-host/utils/native-app-host-capability.util.ts',
  ),
  'utf8',
);
const capabilityName = capabilityUtilSource.match(
  /NATIVE_APP_HOST_CAPABILITY_NAME = '([^']+)'/,
)?.[1];
const supportedCapabilityRange = capabilityUtilSource.match(
  /NATIVE_APP_HOST_SUPPORTED_RANGE = '([^']+)'/,
)?.[1];
if (!capabilityName || !supportedCapabilityRange)
  throw new Error('Could not read the native app host capability contract');
const applications = configuration.applications.map((directory) => {
  const source = path.resolve(root, directory);
  const manifest = JSON.parse(
    readFileSync(path.join(source, 'native-app.json'), 'utf8'),
  );
  if (!/^[a-f0-9-]{36}$/.test(manifest.universalIdentifier))
    throw new Error(
      `Native app ${directory} needs a stable UUID universalIdentifier`,
    );
  if (!semver.valid(manifest.version))
    throw new Error(
      `Native app ${directory} needs a semantic semver version, got "${manifest.version}"`,
    );
  const capabilitySeparator = (manifest.hostCapability ?? '').lastIndexOf('@');
  const declaredCapabilityName =
    capabilitySeparator > 0
      ? manifest.hostCapability.slice(0, capabilitySeparator)
      : null;
  const declaredCapabilityRange =
    capabilitySeparator > 0
      ? manifest.hostCapability.slice(capabilitySeparator + 1)
      : null;
  if (
    declaredCapabilityName !== capabilityName ||
    !declaredCapabilityRange ||
    !semver.validRange(declaredCapabilityRange)
  )
    throw new Error(
      `Native app ${directory} must declare hostCapability "${capabilityName}@<semver range>", got "${manifest.hostCapability}"`,
    );
  if (!semver.subset(declaredCapabilityRange, supportedCapabilityRange))
    throw new Error(
      `Native app ${directory} requires ${manifest.hostCapability} which is not fully covered by ${capabilityName}@${supportedCapabilityRange}`,
    );
  for (const [collection, key] of [
    ['routes', 'path'],
    ['navigation', 'id'],
    ['recordSections', 'id'],
    ['commands', 'key'],
  ]) {
    const identifiers = (manifest[collection] ?? []).map((entry) => entry[key]);
    if (new Set(identifiers).size !== identifiers.length)
      throw new Error(
        `Native app ${directory} declares duplicate ${collection} identifiers`,
      );
  }
  for (const command of manifest.commands ?? []) {
    if (!('label' in command)) continue;
    if (
      !/^[a-f0-9-]{36}$/.test(command.key) ||
      !command.label ||
      !command.shortLabel ||
      !command.icon ||
      !Number.isFinite(command.position) ||
      typeof command.isPinned !== 'boolean' ||
      ![
        'GLOBAL',
        'GLOBAL_OBJECT_CONTEXT',
        'RECORD_SELECTION',
        'FALLBACK',
      ].includes(command.availabilityType)
    )
      throw new Error(`Invalid command menu item in ${directory}`);
  }
  return { source, manifest };
});
if (
  new Set(applications.map(({ manifest }) => manifest.universalIdentifier))
    .size !== applications.length
)
  throw new Error('Duplicate native application identifier');
const routes = new Set();
const commands = new Set();
for (const { source, manifest } of applications) {
  for (const route of manifest.routes ?? []) {
    if (routes.has(route.path))
      throw new Error('Duplicate native route: ' + route.path);
    routes.add(route.path);
  }
  for (const command of manifest.commands ?? []) {
    if (commands.has(command.key))
      throw new Error('Duplicate native command: ' + command.key);
    commands.add(command.key);
  }
  for (const side of ['frontend', 'server']) {
    const directory = path.join(source, 'src', side);
    if (!existsSync(directory)) continue;
    const target = path.join(
      root,
      `packages/twenty-${side === 'frontend' ? 'front' : 'server'}/src/native-apps`,
      manifest.universalIdentifier,
      side,
    );
    for (const file of walk(directory)) {
      if (
        file.includes(`${path.sep}__tests__${path.sep}`) ||
        file.includes(`${path.sep}__stories__${path.sep}`)
      ) {
        continue;
      }
      const content = readFileSync(file, 'utf8');
      for (const [, specifier] of content.matchAll(
        /(?:from\s+|import\s*\()['"]([^'"]+)['"]/g,
      )) {
        if (
          (specifier.startsWith('@/') &&
            !specifier.startsWith('@/app/native-extension-host/')) ||
          specifier.startsWith('~/') ||
          (specifier.startsWith('src/') &&
            !specifier.startsWith(
              'src/engine/core-modules/application/native-extension-host/',
            ))
        )
          throw new Error(`Private host import in ${file}: ${specifier}`);
      }
      write(
        path.join(target, path.relative(directory, file)),
        header + content,
      );
    }
  }
}
const frontRoot = path.join(root, 'packages/twenty-front/src/native-apps');
const serverRoot = path.join(root, 'packages/twenty-server/src/native-apps');
const lazyEntry = (manifest, entry) =>
  `() => import('./${manifest.universalIdentifier}/frontend/${entry.module}').then(module => ({ default: module.${entry.export} }))`;
const registrations = applications
  .map(
    ({ manifest }) => `{
  universalIdentifier: ${JSON.stringify(manifest.universalIdentifier)},
  version: ${JSON.stringify(manifest.version)},
  routes: [${(manifest.routes ?? []).map((entry) => `{ path: ${JSON.stringify(entry.path)}, load: ${lazyEntry(manifest, entry)} }`).join(',')}],
  navigation: [${(manifest.navigation ?? []).map((entry) => `{ id: ${JSON.stringify(entry.id)}, position: ${entry.position}, load: ${lazyEntry(manifest, entry)} }`).join(',')}],
  recordSections: [${(manifest.recordSections ?? []).map((entry) => `{ id: ${JSON.stringify(entry.id)}, position: ${entry.position}, objectNames: ${JSON.stringify(entry.objectNames)}, load: ${lazyEntry(manifest, entry)} }`).join(',')}],
  commands: [${(manifest.commands ?? []).map((entry) => `{ key: ${JSON.stringify(entry.key)}${entry.label ? `, label: ${JSON.stringify(entry.label)}` : ''}${entry.shortLabel ? `, shortLabel: ${JSON.stringify(entry.shortLabel)}` : ''}, load: ${lazyEntry(manifest, entry)} }`).join(',')}],
}`,
  )
  .join(',\n');
write(
  path.join(frontRoot, 'registry.ts'),
  header +
    `import { type NativeAppDefinition } from '@/app/native-extension-host/types/NativeAppDefinition';\nexport const NATIVE_APP_DEFINITIONS: NativeAppDefinition[] = [${registrations}];\n`,
);
write(
  path.join(serverRoot, 'modules.ts'),
  header +
    applications
      .map(
        ({ manifest }, index) =>
          `import { ${manifest.serverExport} as NativeModule${index} } from './${manifest.universalIdentifier}/server/${manifest.serverModule}';`,
      )
      .join('\n') +
    `\nexport const NATIVE_APP_MODULES = [${applications.map((_, index) => `NativeModule${index}`).join(',')}];\n`,
);
write(
  path.join(serverRoot, 'manifests.ts'),
  header +
    `export const NATIVE_APP_MANIFESTS = ${JSON.stringify(
      applications.map(({ manifest }) => manifest),
      null,
      2,
    )} as const;\n`,
);
console.log(
  `Prepared ${applications.length} native application(s) for the Twenty build.`,
);
