// Generated by tools/native-apps/build.mjs. Edit the native app package instead.
import { FieldMetadataType, RelationType } from 'twenty-shared/types';
import { v4 } from 'uuid';

import { type CreateFieldInput } from 'src/engine/core-modules/application/native-extension-host/api/engine/metadata-modules/field-metadata/dtos/create-field.input';
import { type CreateObjectInput } from 'src/engine/core-modules/application/native-extension-host/api/engine/metadata-modules/object-metadata/dtos/create-object.input';
import { camelCase } from 'src/engine/core-modules/application/native-extension-host/api/utils/camel-case';

const RECORD_LIST_ENTRY_OBJECT_NAME_PREFIX = 'recordListEntry';

export const buildRecordListEntryObjectNames = (recordListId: string) => {
  const normalizedRecordListId = recordListId.replace(/-/g, '');
  const nameSingular = camelCase(
    `${RECORD_LIST_ENTRY_OBJECT_NAME_PREFIX}${normalizedRecordListId}`,
  );

  return {
    nameSingular,
    namePlural: `${nameSingular}Collection`,
  };
};

export const buildRecordListEntryObjectInput = ({
  recordListId,
  recordListName,
}: {
  recordListId: string;
  recordListName: string;
}): CreateObjectInput => {
  const { nameSingular, namePlural } =
    buildRecordListEntryObjectNames(recordListId);

  return {
    nameSingular,
    namePlural,
    labelSingular: `${recordListName} entry`,
    labelPlural: `${recordListName} entries`,
    icon: 'IconAddressBook',
    skipNameField: true,
    isLabelSyncedWithName: false,
  };
};

export const buildRecordListSourceRecordFieldInput = ({
  entryObjectMetadataId,
  parentObjectMetadataId,
  parentObjectLabelSingular,
  recordListName,
}: {
  entryObjectMetadataId: string;
  parentObjectMetadataId: string;
  parentObjectLabelSingular: string;
  recordListName: string;
}): Omit<CreateFieldInput, 'workspaceId'> => ({
  type: FieldMetadataType.RELATION,
  name: 'sourceRecord',
  label: parentObjectLabelSingular,
  icon: 'IconAddressBook',
  objectMetadataId: entryObjectMetadataId,
  isNullable: true,
  isUnique: false,
  relationCreationPayload: {
    type: RelationType.MANY_TO_ONE,
    targetObjectMetadataId: parentObjectMetadataId,
    targetFieldLabel: `${recordListName} entries`,
    targetFieldIcon: 'IconList',
  },
});

export const buildRecordListDefaultStatusFieldInput = ({
  entryObjectMetadataId,
}: {
  entryObjectMetadataId: string;
}): Omit<CreateFieldInput, 'workspaceId'> => ({
  type: FieldMetadataType.SELECT,
  name: 'status',
  label: 'Status',
  icon: 'IconStatus',
  objectMetadataId: entryObjectMetadataId,
  isNullable: true,
  isUnique: false,
  defaultValue: "'NEW'",
  options: [
    { id: v4(), label: 'New', value: 'NEW', position: 0, color: 'gray' },
    { id: v4(), label: 'In progress', value: 'IN_PROGRESS', position: 1, color: 'blue' },
    { id: v4(), label: 'Done', value: 'DONE', position: 2, color: 'green' },
  ],
});
