// Generated by tools/native-apps/build.mjs. Edit the native app package instead.
import {
  type RecordListTemplate,
  type RecordListTemplateField,
} from '../constants/recordListTemplates';

const CUSTOM_TEMPLATES_STORAGE_KEY = 'twenty-list-view-custom-templates';
export const CUSTOM_RECORD_LIST_TEMPLATES_UPDATED_EVENT =
  'custom-record-list-templates-updated';

const isTemplateField = (value: unknown): value is RecordListTemplateField => {
  if (typeof value !== 'object' || value === null) {
    return false;
  }

  const field = value as Record<string, unknown>;

  return (
    typeof field.name === 'string' &&
    typeof field.label === 'string' &&
    typeof field.type === 'string' &&
    typeof field.icon === 'string' &&
    (field.options === undefined ||
      (Array.isArray(field.options) &&
        field.options.every(
          (option) =>
            typeof option === 'object' &&
            option !== null &&
            typeof option.label === 'string' &&
            typeof option.value === 'string' &&
            typeof option.color === 'string',
        )))
  );
};

const isCustomRecordListTemplate = (
  value: unknown,
): value is RecordListTemplate => {
  if (typeof value !== 'object' || value === null) {
    return false;
  }

  const template = value as Record<string, unknown>;

  return (
    typeof template.key === 'string' &&
    template.key.startsWith('custom:') &&
    typeof template.title === 'string' &&
    typeof template.description === 'string' &&
    typeof template.icon === 'string' &&
    typeof template.suggestedObjectNameSingular === 'string' &&
    Array.isArray(template.categories) &&
    template.categories.every((category) => typeof category === 'string') &&
    Array.isArray(template.fieldLabels) &&
    template.fieldLabels.every(
      (fieldLabel) => typeof fieldLabel === 'string',
    ) &&
    Array.isArray(template.templateFields) &&
    template.templateFields.every(isTemplateField)
  );
};

export const getSavedCustomRecordListTemplates = (): RecordListTemplate[] => {
  if (typeof window === 'undefined') {
    return [];
  }

  try {
    const storedTemplates = window.localStorage.getItem(
      CUSTOM_TEMPLATES_STORAGE_KEY,
    );
    const parsedTemplates: unknown = storedTemplates
      ? JSON.parse(storedTemplates)
      : [];

    return Array.isArray(parsedTemplates)
      ? parsedTemplates.filter(isCustomRecordListTemplate)
      : [];
  } catch {
    return [];
  }
};

export const saveCustomRecordListTemplate = (
  template: RecordListTemplate,
): RecordListTemplate[] => {
  const nextTemplates = [
    template,
    ...getSavedCustomRecordListTemplates().filter(
      (savedTemplate) => savedTemplate.key !== template.key,
    ),
  ];

  window.localStorage.setItem(
    CUSTOM_TEMPLATES_STORAGE_KEY,
    JSON.stringify(nextTemplates),
  );
  window.dispatchEvent(new Event(CUSTOM_RECORD_LIST_TEMPLATES_UPDATED_EVENT));

  return nextTemplates;
};
