// Generated by tools/native-apps/build.mjs. Edit the native app package instead.
import { Injectable } from '@nestjs/common';

export const HOST_SAMPLE_APPLICATION_ID =
  '5f1d0c2e-9a44-4a3b-8f2f-6a1b2c3d4e5f';

@Injectable()
export class HostSampleService {
  // The sample app owns no records. Its service only proves that an app server
  // module can be registered, wired through the host and inspected per
  // workspace.
  getMarker(workspaceId: string) {
    return `native-host-sample:${workspaceId}`;
  }
}
