// Generated by tools/native-apps/build.mjs. Edit the native app package instead.
import { t } from '@lingui/core/macro';

import { getEditableRecordListTemplateFields } from './editableRecordListTemplateFields';

export type RecordListTemplateKey =
  | 'OUTREACH_TRACKER'
  | 'NEWSLETTER'
  | 'PRESS_OUTREACH'
  | 'MA_ADVISER_NEWSLETTER'
  | 'RECRUITING'
  | 'OUTSOURCING'
  | 'FUNDRAISING'
  | 'VC_DEALFLOW'
  | 'EMPLOYEE_ONBOARDING';

export type RecordListTemplateField = {
  name: string;
  label: string;
  type: string;
  icon: string;
  options?: Array<{
    label: string;
    value: string;
    color: string;
  }>;
};

export type RecordListTemplate = {
  key: string;
  templateKey?: RecordListTemplateKey;
  title: string;
  description: string;
  icon: string;
  suggestedObjectNameSingular: string;
  categories: string[];
  fieldLabels: string[];
  templateFields?: RecordListTemplateField[];
};

export const getRecordListTemplates = (): RecordListTemplate[] => {
  const templates: RecordListTemplate[] = [
    {
      key: 'OUTREACH_TRACKER',
      title: t`Outreach tracker`,
      description: t`Track contacts, follow-ups and responses across every outreach channel.`,
      icon: 'IconTargetArrow',
      suggestedObjectNameSingular: 'person',
      categories: [t`Sales`, t`Marketing`],
      fieldLabels: [
        t`Status`,
        t`Channel`,
        t`Priority`,
        t`Last contacted`,
        t`Next follow-up`,
        t`Notes`,
      ],
    },
    {
      key: 'NEWSLETTER',
      title: t`Newsletter`,
      description: t`Manage newsletter audiences, send dates and engagement in one reusable workflow.`,
      icon: 'IconMail',
      suggestedObjectNameSingular: 'person',
      categories: [t`Marketing`],
      fieldLabels: [
        t`Status`,
        t`Newsletter type`,
        t`Audience`,
        t`Planned send date`,
        t`Sent at`,
        t`Campaign link`,
        t`Notes`,
      ],
    },
    {
      key: 'PRESS_OUTREACH',
      title: t`Press outreach`,
      description: t`Manage media contacts, pitches and follow-ups for a campaign or announcement.`,
      icon: 'IconBroadcast',
      suggestedObjectNameSingular: 'person',
      categories: [t`PR`, t`Marketing`],
      fieldLabels: [
        t`Status`,
        t`Publication`,
        t`Campaign angle`,
        t`Outreach type`,
        t`Pitch date`,
        t`Follow-up date`,
        t`Coverage link`,
        t`Notes`,
      ],
    },
    {
      key: 'MA_ADVISER_NEWSLETTER',
      title: t`M&A adviser newsletter`,
      description: t`Maintain a qualified adviser network by focus, geography and typical deal size.`,
      icon: 'IconBuildingBank',
      suggestedObjectNameSingular: 'company',
      categories: [t`Finance`, t`Sales`],
      fieldLabels: [
        t`Status`,
        t`Adviser type`,
        t`Sector focus`,
        t`Geography`,
        t`Typical deal size`,
        t`Last newsletter`,
        t`Next follow-up`,
        t`Notes`,
      ],
    },
    {
      key: 'RECRUITING',
      title: t`Recruiting`,
      description: t`Track candidates from sourcing through interviews, decisions and offers.`,
      icon: 'IconUsers',
      suggestedObjectNameSingular: 'person',
      categories: [t`HR`, t`Recruiting`],
      fieldLabels: [
        t`Status`,
        t`Role`,
        t`Source`,
        t`Stage`,
        t`Next interview`,
        t`Owner`,
        t`Notes`,
      ],
    },
    {
      key: 'OUTSOURCING',
      title: t`Outsourcing`,
      description: t`Organize freelance contacts, their skills, projects and availability.`,
      icon: 'IconBriefcase',
      suggestedObjectNameSingular: 'person',
      categories: [t`Operations`, t`Recruiting`],
      fieldLabels: [
        t`Status`,
        t`Skills`,
        t`Specialty`,
        t`Hourly rate`,
        t`Availability`,
        t`Last project`,
        t`Notes`,
      ],
    },
    {
      key: 'FUNDRAISING',
      title: t`Fundraising`,
      description: t`Manage investor relationships, outreach, meetings and fundraising progress.`,
      icon: 'IconBuildingBank',
      suggestedObjectNameSingular: 'company',
      categories: [t`Fundraising`, t`Finance`, t`Startups`],
      fieldLabels: [
        t`Status`,
        t`Investor`,
        t`Round`,
        t`Stage`,
        t`Last contacted`,
        t`Next meeting`,
        t`Amount`,
        t`Notes`,
      ],
    },
    {
      key: 'VC_DEALFLOW',
      title: t`VC dealflow`,
      description: t`Review investment opportunities by stage, sector, fit and next step.`,
      icon: 'IconChartDots3',
      suggestedObjectNameSingular: 'company',
      categories: [t`Venture Capital`, t`Investing`, t`Finance`],
      fieldLabels: [
        t`Status`,
        t`Deal stage`,
        t`Sector`,
        t`Source`,
        t`Priority`,
        t`Last reviewed`,
        t`Next step`,
      ],
    },
    {
      key: 'EMPLOYEE_ONBOARDING',
      title: t`Employee onboarding`,
      description: t`Give every new hire a clear path through onboarding and key milestones.`,
      icon: 'IconUserPlus',
      suggestedObjectNameSingular: 'person',
      categories: [t`HR`, t`Operations`],
      fieldLabels: [
        t`Status`,
        t`Role`,
        t`Start date`,
        t`Manager`,
        t`Equipment`,
        t`Training`,
        t`Next check-in`,
      ],
    },
  ];

  return templates.map((template) => ({
    ...template,
    templateKey: template.key as RecordListTemplateKey,
    templateFields: getEditableRecordListTemplateFields(
      template.key as RecordListTemplateKey,
      template.fieldLabels,
    ),
  }));
};
