// Generated by tools/native-apps/build.mjs. Edit the native app package instead.
export type RecordListViewDisplaySettings = {
  showAttributeLabels: boolean;
  hideEmptyAttributes: boolean;
};

export const DEFAULT_RECORD_LIST_VIEW_DISPLAY_SETTINGS: RecordListViewDisplaySettings =
  {
    showAttributeLabels: false,
    hideEmptyAttributes: false,
  };
