// Generated by tools/native-apps/build.mjs. Edit the native app package instead.
import { styled } from '@linaria/react';
import { t } from '@lingui/core/macro';
import { useEffect, useRef, useState } from 'react';
import { useParams, useSearchParams } from 'react-router-dom';
import { AppPath, ContextStorePageType } from 'twenty-shared/types';
import { getAppPath, isDefined } from 'twenty-shared/utils';
import { Button } from 'twenty-ui/primitives/input';
import { LightIconButton } from 'twenty-ui/components';
import { IconList, IconPlus, IconSettings, useIcons } from 'twenty-ui/icon';
import { themeCssVariables } from 'twenty-ui/theme';

import { contextStoreCurrentObjectMetadataItemIdComponentState } from '@/app/native-extension-host/api/modules/context-store/states/contextStoreCurrentObjectMetadataItemIdComponentState';
import { contextStoreCurrentPageTypeComponentState } from '@/app/native-extension-host/api/modules/context-store/states/contextStoreCurrentPageTypeComponentState';
import { contextStoreCurrentViewIdComponentState } from '@/app/native-extension-host/api/modules/context-store/states/contextStoreCurrentViewIdComponentState';
import { contextStoreCurrentViewTypeComponentState } from '@/app/native-extension-host/api/modules/context-store/states/contextStoreCurrentViewTypeComponentState';
import { ContextStoreViewType } from '@/app/native-extension-host/api/modules/context-store/types/ContextStoreViewType';
import { useFilteredObjectMetadataItems } from '@/app/native-extension-host/api/modules/object-metadata/hooks/useFilteredObjectMetadataItems';
import { type EnrichedObjectMetadataItem } from '@/app/native-extension-host/api/modules/object-metadata/types/EnrichedObjectMetadataItem';
import { RecordIndexContainerGater } from '@/app/native-extension-host/api/modules/object-record/record-index/components/RecordIndexContainerGater';
import { RecordIndexCommandMenu } from '@/app/native-extension-host/api/modules/command-menu-item/components/RecordIndexCommandMenu';
import { useRefetchFindManyRecords } from '@/app/native-extension-host/api/modules/object-record/hooks/useRefetchFindManyRecords';
import { useOpenObjectRecordsSpreadsheetImportDialog } from '@/app/native-extension-host/api/modules/object-record/spreadsheet-import/hooks/useOpenObjectRecordsSpreadsheetImportDialog';
import { useHasPermissionFlag } from '@/app/native-extension-host/api/modules/auth/hooks/useHasPermissionFlag';
import { AddRecordToListModal } from './components/AddRecordToListModal';
import { RecordListSettingsModal } from './components/RecordListSettingsModal';
import { RecordListOptionsPage } from './components/RecordListOptionsPage';
import { RecordListRelatedFieldSyncEffect } from './components/RecordListRelatedFieldSyncEffect';
import { ADD_RECORD_TO_LIST_MODAL_ID } from './constants/AddRecordToListModalId';
import { RECORD_LIST_SETTINGS_MODAL_ID } from './constants/RecordListSettingsModalId';
import { useRecordList } from './hooks/useRecordList';
import { type RecordList } from './types/RecordList';
import { useModal } from '@/app/native-extension-host/api/modules/ui/layout/modal/hooks/useModal';
import { PageContainer } from '@/app/native-extension-host/api/modules/ui/layout/page/components/PageContainer';
import { PageCardHeader } from '@/app/native-extension-host/api/modules/ui/layout/page/components/PageCardHeader';
import { useAtomComponentState } from '@/app/native-extension-host/api/modules/ui/utilities/state/jotai/hooks/useAtomComponentState';
import { useAtomStateValue } from '@/app/native-extension-host/api/modules/ui/utilities/state/jotai/hooks/useAtomStateValue';
import { viewsSelector } from '@/app/native-extension-host/api/modules/views/states/selectors/viewsSelector';
import { ViewType } from '@/app/native-extension-host/api/modules/views/types/ViewType';
import {
  PermissionFlagType,
  ViewKey,
} from '@/app/native-extension-host/api/generated-metadata/graphql';
import { useGlobalHotkeys } from '@/app/native-extension-host/api/modules/ui/utilities/hotkey/hooks/useGlobalHotkeys';
import { recordStoreFamilyState } from '@/app/native-extension-host/api/modules/object-record/record-store/states/recordStoreFamilyState';
import { useStore } from 'jotai';
import { useOpenRecordInSidePanel } from '@/app/native-extension-host/api/modules/side-panel/hooks/useOpenRecordInSidePanel';
import { RecordBoardCardDisplaySettingsContext } from '@/app/native-extension-host/api/modules/object-record/record-board/contexts/RecordBoardCardDisplaySettingsContext';
import { useRecordListEntries } from './hooks/useRecordListEntries';
import {
  DEFAULT_RECORD_LIST_VIEW_DISPLAY_SETTINGS,
  type RecordListViewDisplaySettings,
} from './types/RecordListViewDisplaySettings';
import { useAddRecordsToList } from './hooks/useAddRecordsToList';
import { useSnackBar } from '@/app/native-extension-host/api/modules/ui/feedback/snack-bar-manager/hooks/useSnackBar';
import { RecordListImportExportDropdown } from './components/RecordListImportExportDropdown';

const getRecordListViewDisplaySettings = (
  viewId: string,
): RecordListViewDisplaySettings => {
  try {
    const storedSettings = window.localStorage.getItem(
      `twenty-list-view-display-settings:${viewId}`,
    );
    if (storedSettings === null) {
      return DEFAULT_RECORD_LIST_VIEW_DISPLAY_SETTINGS;
    }

    const parsedSettings: unknown = JSON.parse(storedSettings);
    if (
      typeof parsedSettings === 'object' &&
      parsedSettings !== null &&
      'showAttributeLabels' in parsedSettings &&
      'hideEmptyAttributes' in parsedSettings &&
      typeof parsedSettings.showAttributeLabels === 'boolean' &&
      typeof parsedSettings.hideEmptyAttributes === 'boolean'
    ) {
      return {
        showAttributeLabels: parsedSettings.showAttributeLabels,
        hideEmptyAttributes: parsedSettings.hideEmptyAttributes,
      };
    }
  } catch {
    return DEFAULT_RECORD_LIST_VIEW_DISPLAY_SETTINGS;
  }

  return DEFAULT_RECORD_LIST_VIEW_DISPLAY_SETTINGS;
};

const StyledStatus = styled.div`
  align-items: center;
  color: ${themeCssVariables.font.color.tertiary};
  display: flex;
  flex: 1;
  justify-content: center;
`;

export const RecordListPage = () => {
  const { recordListId = '' } = useParams<{ recordListId: string }>();
  const { recordList, loading, error, refetch } = useRecordList(recordListId);
  const { findObjectMetadataItemById } = useFilteredObjectMetadataItems();

  if (loading) {
    return <StyledStatus>{t`Loading list…`}</StyledStatus>;
  }

  if (isDefined(error)) {
    return (
      <StyledStatus role="alert">
        {t`The list could not be loaded.`}
        <Button variant="outline" onClick={() => void refetch()}>
          {t`Try again`}
        </Button>
      </StyledStatus>
    );
  }

  if (!isDefined(recordList)) {
    return <StyledStatus>{t`List not found`}</StyledStatus>;
  }

  const parentObjectMetadataItem = findObjectMetadataItemById(
    recordList.parentObjectMetadataId,
  );
  const entryObjectMetadataItem = findObjectMetadataItemById(
    recordList.entryObjectMetadataId,
  );

  if (
    !isDefined(parentObjectMetadataItem) ||
    !isDefined(entryObjectMetadataItem)
  ) {
    return <StyledStatus>{t`List object not found`}</StyledStatus>;
  }

  return (
    <RecordListPageContent
      recordList={recordList}
      parentObjectMetadataItem={parentObjectMetadataItem}
      entryObjectMetadataItem={entryObjectMetadataItem}
    />
  );
};

const RecordListPageContent = ({
  recordList,
  parentObjectMetadataItem,
  entryObjectMetadataItem,
}: {
  recordList: RecordList;
  parentObjectMetadataItem: EnrichedObjectMetadataItem;
  entryObjectMetadataItem: EnrichedObjectMetadataItem;
}) => {
  const listIndexRef = useRef<HTMLDivElement>(null);
  const { openModal } = useModal();
  const { getIcon } = useIcons();
  const [searchParams] = useSearchParams();
  const store = useStore();
  const canImportCsv = useHasPermissionFlag(PermissionFlagType.IMPORT_CSV);
  const { openRecordInSidePanel } = useOpenRecordInSidePanel();
  const { addRecordsToList } = useAddRecordsToList();
  const { enqueueErrorSnackBar, enqueueSuccessSnackBar } = useSnackBar();
  const { openObjectRecordsSpreadsheetImportDialog } =
    useOpenObjectRecordsSpreadsheetImportDialog(
      parentObjectMetadataItem.nameSingular,
    );
  const views = useAtomStateValue(viewsSelector);
  const { refetchFindManyRecords } = useRefetchFindManyRecords({
    objectMetadataNamePlural: entryObjectMetadataItem.namePlural,
    includeAggregateQueries: true,
  });
  const { recordListEntries } = useRecordListEntries(recordList.id);
  const sourceRecordIdByEntryId = new Map(
    recordListEntries.map(({ id, sourceRecordId }) => [id, sourceRecordId]),
  );
  const handleImportCsv = () => {
    openObjectRecordsSpreadsheetImportDialog({
      onRecordsImported: async (records) => {
        if (records.length === 0) {
          return;
        }

        const result = await addRecordsToList({
          recordListId: recordList.id,
          sourceRecordIds: records.map((record) => record.id),
          parentObjectMetadataId: parentObjectMetadataItem.id,
        });

        if (!isDefined(result)) {
          enqueueErrorSnackBar({
            message: t`Import finished but list assignment failed`,
          });
          return;
        }

        await refetchFindManyRecords();
        enqueueSuccessSnackBar({
          message:
            result.skippedCount > 0
              ? t`${result.addedCount} records imported; ${result.skippedCount} already in list`
              : t`${result.addedCount} records imported to list`,
        });
      },
    });
  };

  useGlobalHotkeys({
    keys: 'e',
    containsModifier: false,
    callback: () => openModal(ADD_RECORD_TO_LIST_MODAL_ID),
    options: {
      enableOnContentEditable: false,
      enableOnFormTags: false,
    },
  });

  const listViews = views.filter(
    (view) =>
      view.objectMetadataId === entryObjectMetadataItem.id &&
      view.type !== ViewType.FIELDS_WIDGET,
  );
  const viewFromUrl = listViews.find(
    (view) => view.id === searchParams.get('viewId'),
  );
  const defaultView = listViews.find(
    (view) => view.id === recordList.defaultViewId,
  );
  const indexView = listViews.find((view) => view.key === ViewKey.INDEX);
  const currentView = viewFromUrl ?? defaultView ?? indexView ?? listViews[0];

  const [displaySettingsByViewId, setDisplaySettingsByViewId] = useState<
    Record<string, RecordListViewDisplaySettings>
  >(() =>
    currentView
      ? { [currentView.id]: getRecordListViewDisplaySettings(currentView.id) }
      : {},
  );

  const [contextStoreCurrentObjectMetadataItemId, setObjectMetadataItemId] =
    useAtomComponentState(
      contextStoreCurrentObjectMetadataItemIdComponentState,
    );
  const [contextStoreCurrentViewId, setCurrentViewId] = useAtomComponentState(
    contextStoreCurrentViewIdComponentState,
  );
  const [contextStoreCurrentViewType, setCurrentViewType] =
    useAtomComponentState(contextStoreCurrentViewTypeComponentState);
  const [contextStoreCurrentPageType, setCurrentPageType] =
    useAtomComponentState(contextStoreCurrentPageTypeComponentState);

  const targetViewType =
    currentView?.type === ViewType.KANBAN
      ? ContextStoreViewType.Kanban
      : ContextStoreViewType.Table;
  const isContextReady =
    contextStoreCurrentObjectMetadataItemId === entryObjectMetadataItem.id &&
    contextStoreCurrentViewId === currentView?.id &&
    contextStoreCurrentViewType === targetViewType &&
    contextStoreCurrentPageType === ContextStorePageType.Index;

  useEffect(() => {
    setObjectMetadataItemId(entryObjectMetadataItem.id);
    setCurrentViewId(currentView?.id);
    setCurrentViewType(targetViewType);
    setCurrentPageType(ContextStorePageType.Index);
  }, [
    currentView?.id,
    entryObjectMetadataItem.id,
    setCurrentPageType,
    setCurrentViewId,
    setCurrentViewType,
    setObjectMetadataItemId,
    targetViewType,
  ]);

  if (!isDefined(currentView)) {
    return <StyledStatus>{t`No view available for this list`}</StyledStatus>;
  }

  const getSourceRecordId = (entryRecordId: string) => {
    const sourceRecordId = sourceRecordIdByEntryId.get(entryRecordId);

    if (isDefined(sourceRecordId)) {
      return sourceRecordId;
    }

    const sourceRecord = store.get(
      recordStoreFamilyState.atomFamily(entryRecordId),
    )?.sourceRecord;

    return isDefined(sourceRecord) &&
      typeof sourceRecord === 'object' &&
      'id' in sourceRecord &&
      typeof sourceRecord.id === 'string'
      ? sourceRecord.id
      : null;
  };

  if (!isContextReady) {
    return <StyledStatus>{t`Loading list…`}</StyledStatus>;
  }

  const ListIcon = isDefined(recordList.icon)
    ? getIcon(recordList.icon)
    : IconList;

  const header = (
    <PageCardHeader
      icon={<ListIcon size={20} />}
      title={recordList.name}
      actionButton={
        <>
          <RecordIndexCommandMenu />
          <LightIconButton
            aria-label={t`List settings`}
            size="sm"
            onClick={() => openModal(RECORD_LIST_SETTINGS_MODAL_ID)}
          >
            <IconSettings />
          </LightIconButton>
          <Button
            startIcon={<IconPlus />}
            color="accent"
            variant="solid"
            size="sm"
            onClick={() => openModal(ADD_RECORD_TO_LIST_MODAL_ID)}
          >
            {t`Add ${parentObjectMetadataItem.labelPlural}`}
          </Button>
          <RecordListImportExportDropdown
            filename={recordList.name}
            canImportCsv={canImportCsv}
            onImportCsv={handleImportCsv}
          />
        </>
      }
    />
  );

  const displaySettings =
    displaySettingsByViewId[currentView.id] ??
    getRecordListViewDisplaySettings(currentView.id);

  const handleDisplaySettingsChange = (
    setting: keyof RecordListViewDisplaySettings,
    value: boolean,
  ) => {
    const nextSettings = { ...displaySettings, [setting]: value };
    setDisplaySettingsByViewId((previousSettingsByViewId) => ({
      ...previousSettingsByViewId,
      [currentView.id]: nextSettings,
    }));
    window.localStorage.setItem(
      `twenty-list-view-display-settings:${currentView.id}`,
      JSON.stringify(nextSettings),
    );
  };

  return (
    <PageContainer>
      <RecordBoardCardDisplaySettingsContext.Provider value={displaySettings}>
        <RecordListRelatedFieldSyncEffect
          recordListId={recordList.id}
          parentObjectMetadataItem={parentObjectMetadataItem}
          entryObjectMetadataItem={entryObjectMetadataItem}
          getSourceRecordId={getSourceRecordId}
        />
        <div ref={listIndexRef} style={{ display: 'contents' }}>
          <RecordIndexContainerGater
            header={header}
            indexIdentifierUrl={(entryRecordId) => {
              const sourceRecordId = getSourceRecordId(entryRecordId);

              return isDefined(sourceRecordId)
                ? getAppPath(AppPath.RecordShowPage, {
                    objectNameSingular: parentObjectMetadataItem.nameSingular,
                    objectRecordId: sourceRecordId,
                  })
                : '#';
            }}
            isRecordCreationDisabled
            onOpenRecord={(entryRecordId) => {
              const sourceRecordId = getSourceRecordId(entryRecordId);

              if (isDefined(sourceRecordId)) {
                openRecordInSidePanel({
                  recordId: sourceRecordId,
                  objectNameSingular: parentObjectMetadataItem.nameSingular,
                });
              }
            }}
            pageTitle={recordList.name}
            optionsDropdownAdditionalPage={{
              label: t`Attributes`,
              content: (
                <RecordListOptionsPage
                  recordListId={recordList.id}
                  parentObjectMetadataItem={parentObjectMetadataItem}
                  objectMetadataItem={entryObjectMetadataItem}
                  displaySettings={displaySettings}
                  isKanbanView={currentView.type === ViewType.KANBAN}
                  visibleFieldMetadataIds={currentView.viewFields
                    .filter(
                      (viewField) => viewField.isActive && viewField.isVisible,
                    )
                    .map((viewField) => viewField.fieldMetadataId)}
                  onDisplaySettingsChange={handleDisplaySettingsChange}
                />
              ),
            }}
          />
        </div>
      </RecordBoardCardDisplaySettingsContext.Provider>
      <AddRecordToListModal
        recordListId={recordList.id}
        parentObjectMetadataId={parentObjectMetadataItem.id}
        objectNameSingular={parentObjectMetadataItem.nameSingular}
        objectLabelPlural={parentObjectMetadataItem.labelPlural}
        objectLabelSingular={parentObjectMetadataItem.labelSingular}
        onRecordsAdded={() => {
          void refetchFindManyRecords().catch(() => undefined);
        }}
      />
      <RecordListSettingsModal
        recordList={recordList}
        objectLabelPlural={parentObjectMetadataItem.labelPlural}
      />
    </PageContainer>
  );
};
