import { defineIndex } from 'twenty-sdk/define';

import {
  RECORD_LIST_ENTRY_LIST_FIELD_UNIVERSAL_IDENTIFIER,
  RECORD_LIST_ENTRY_LIST_PERSON_INDEX_LIST_FIELD_UNIVERSAL_IDENTIFIER,
  RECORD_LIST_ENTRY_LIST_PERSON_INDEX_PERSON_FIELD_UNIVERSAL_IDENTIFIER,
  RECORD_LIST_ENTRY_LIST_PERSON_INDEX_UNIVERSAL_IDENTIFIER,
  RECORD_LIST_ENTRY_OBJECT_UNIVERSAL_IDENTIFIER,
  RECORD_LIST_ENTRY_PERSON_FIELD_UNIVERSAL_IDENTIFIER,
} from 'src/constants/universal-identifiers';

export default defineIndex({
  universalIdentifier: RECORD_LIST_ENTRY_LIST_PERSON_INDEX_UNIVERSAL_IDENTIFIER,
  objectUniversalIdentifier: RECORD_LIST_ENTRY_OBJECT_UNIVERSAL_IDENTIFIER,
  isUnique: true,
  fields: [
    {
      universalIdentifier:
        RECORD_LIST_ENTRY_LIST_PERSON_INDEX_LIST_FIELD_UNIVERSAL_IDENTIFIER,
      fieldUniversalIdentifier:
        RECORD_LIST_ENTRY_LIST_FIELD_UNIVERSAL_IDENTIFIER,
    },
    {
      universalIdentifier:
        RECORD_LIST_ENTRY_LIST_PERSON_INDEX_PERSON_FIELD_UNIVERSAL_IDENTIFIER,
      fieldUniversalIdentifier:
        RECORD_LIST_ENTRY_PERSON_FIELD_UNIVERSAL_IDENTIFIER,
    },
  ],
});
