// Generated by tools/native-apps/build.mjs. Edit the native app package instead.
export const ADD_DEFAULT_VIEW_TO_RECORD_LIST_UPGRADE_COMMAND_NAME =
  '2.39.0_AddDefaultViewToRecordListFastInstanceCommand_1790261967024';
