// Generated by tools/native-apps/build.mjs. Edit the native app package instead.
import { FieldMetadataType } from 'twenty-shared/types';
import { v4 } from 'uuid';

import { getRecordListSelectOptionValue } from '../utils/get-record-list-select-option-value';
import { type CreateFieldInput } from 'src/engine/core-modules/application/native-extension-host/api/engine/metadata-modules/field-metadata/dtos/create-field.input';

export const RECORD_LIST_TEMPLATE_KEYS = [
  'OUTREACH_TRACKER',
  'NEWSLETTER',
  'PRESS_OUTREACH',
  'MA_ADVISER_NEWSLETTER',
  'RECRUITING',
  'OUTSOURCING',
  'FUNDRAISING',
  'VC_DEALFLOW',
  'EMPLOYEE_ONBOARDING',
] as const;

export type RecordListTemplateKey = (typeof RECORD_LIST_TEMPLATE_KEYS)[number];

type RecordListTemplateField = Omit<
  CreateFieldInput,
  'workspaceId' | 'objectMetadataId'
>;

const buildSelectField = ({
  name,
  label,
  icon,
  optionLabels,
}: {
  name: string;
  label: string;
  icon: string;
  optionLabels: string[];
}): RecordListTemplateField => {
  const optionValues: string[] = [];

  return {
    type: FieldMetadataType.SELECT,
    name,
    label,
    icon,
    isNullable: true,
    isUnique: false,
    options: optionLabels.map((optionLabel, position) => {
      const value = getRecordListSelectOptionValue(optionLabel, optionValues);

      optionValues.push(value);

      return {
        id: v4(),
        label: optionLabel,
        value,
        position,
        color: ['gray', 'blue', 'purple', 'orange', 'green', 'red'][
          position % 6
        ],
      };
    }),
  };
};

const buildTextField = ({
  name,
  label,
  icon = 'IconTextSize',
}: {
  name: string;
  label: string;
  icon?: string;
}): RecordListTemplateField => ({
  type: FieldMetadataType.TEXT,
  name,
  label,
  icon,
  isNullable: true,
  isUnique: false,
});

const buildDateField = ({
  name,
  label,
}: {
  name: string;
  label: string;
}): RecordListTemplateField => ({
  type: FieldMetadataType.DATE,
  name,
  label,
  icon: 'IconCalendarEvent',
  isNullable: true,
  isUnique: false,
});

const buildStatusField = (optionLabels: string[]): RecordListTemplateField => {
  const field = buildSelectField({
    name: 'status',
    label: 'Status',
    icon: 'IconStatus',
    optionLabels,
  });

  return {
    ...field,
    defaultValue: `'${field.options?.[0]?.value ?? ''}'`,
  };
};

const buildRecordListTemplateFields = (): Record<
  RecordListTemplateKey,
  RecordListTemplateField[]
> => ({
  OUTREACH_TRACKER: [
    buildStatusField([
      'To research',
      'Ready to contact',
      'Contacted',
      'Follow-up',
      'Responded',
      'Completed',
      'Not relevant',
    ]),
    buildSelectField({
      name: 'channel',
      label: 'Channel',
      icon: 'IconSend',
      optionLabels: ['Email', 'LinkedIn', 'Phone', 'Event', 'Introduction'],
    }),
    buildSelectField({
      name: 'priority',
      label: 'Priority',
      icon: 'IconFlag',
      optionLabels: ['Low', 'Medium', 'High'],
    }),
    buildDateField({ name: 'lastContactedAt', label: 'Last contacted' }),
    buildDateField({ name: 'nextFollowUpAt', label: 'Next follow-up' }),
    buildTextField({ name: 'ownerNotes', label: 'Notes', icon: 'IconNotes' }),
  ],
  NEWSLETTER: [
    buildStatusField([
      'Planned',
      'Preparing',
      'Ready',
      'Sent',
      'Responded',
      'Unsubscribed',
    ]),
    buildSelectField({
      name: 'newsletterType',
      label: 'Newsletter type',
      icon: 'IconMail',
      optionLabels: [
        'Firm news',
        'Portfolio news',
        'Thought leadership',
        'Event',
      ],
    }),
    buildSelectField({
      name: 'audience',
      label: 'Audience',
      icon: 'IconUsers',
      optionLabels: ['Investors', 'Advisers', 'Founders', 'Media', 'Other'],
    }),
    buildDateField({ name: 'plannedSendDate', label: 'Planned send date' }),
    buildDateField({ name: 'sentAt', label: 'Sent at' }),
    buildTextField({
      name: 'campaignLink',
      label: 'Campaign link',
      icon: 'IconLink',
    }),
    buildTextField({ name: 'notes', label: 'Notes', icon: 'IconNotes' }),
  ],
  PRESS_OUTREACH: [
    buildStatusField([
      'To research',
      'Pitch ready',
      'Contacted',
      'Follow-up',
      'Interested',
      'Published',
      'Passed',
    ]),
    buildTextField({ name: 'publication', label: 'Publication' }),
    buildTextField({ name: 'campaignAngle', label: 'Campaign angle' }),
    buildSelectField({
      name: 'outreachType',
      label: 'Outreach type',
      icon: 'IconSend',
      optionLabels: [
        'Firm announcement',
        'Acquisition',
        'Exit',
        'Portfolio news',
        'Thought leadership',
      ],
    }),
    buildDateField({ name: 'pitchDate', label: 'Pitch date' }),
    buildDateField({ name: 'followUpDate', label: 'Follow-up date' }),
    buildTextField({
      name: 'coverageLink',
      label: 'Coverage link',
      icon: 'IconLink',
    }),
    buildTextField({ name: 'notes', label: 'Notes', icon: 'IconNotes' }),
  ],
  MA_ADVISER_NEWSLETTER: [
    buildStatusField([
      'To qualify',
      'Qualified',
      'Subscribed',
      'Contacted',
      'Responded',
      'Do not contact',
    ]),
    buildSelectField({
      name: 'adviserType',
      label: 'Adviser type',
      icon: 'IconBuildingBank',
      optionLabels: [
        'Investment bank',
        'M&A boutique',
        'Corporate finance',
        'Debt adviser',
        'Other',
      ],
    }),
    buildTextField({ name: 'sectorFocus', label: 'Sector focus' }),
    buildTextField({ name: 'geography', label: 'Geography' }),
    buildSelectField({
      name: 'dealSize',
      label: 'Typical deal size',
      icon: 'IconCurrencyEuro',
      optionLabels: ['Below €25m', '€25–50m', '€50–100m', 'Above €100m'],
    }),
    buildDateField({ name: 'lastNewsletterAt', label: 'Last newsletter' }),
    buildDateField({ name: 'nextFollowUpAt', label: 'Next follow-up' }),
    buildTextField({ name: 'notes', label: 'Notes', icon: 'IconNotes' }),
  ],
  RECRUITING: [
    buildStatusField([
      'Sourced',
      'Screening',
      'Interviewing',
      'Offer',
      'Hired',
      'Rejected',
    ]),
    buildTextField({ name: 'role', label: 'Role' }),
    buildSelectField({
      name: 'source',
      label: 'Source',
      icon: 'IconTargetArrow',
      optionLabels: [
        'Referral',
        'LinkedIn',
        'Job board',
        'Careers page',
        'Other',
      ],
    }),
    buildSelectField({
      name: 'interviewStage',
      label: 'Stage',
      icon: 'IconFlag',
      optionLabels: ['Screen', 'First round', 'Final round', 'References'],
    }),
    buildDateField({ name: 'nextInterviewAt', label: 'Next interview' }),
    buildTextField({ name: 'owner', label: 'Owner' }),
    buildTextField({ name: 'notes', label: 'Notes', icon: 'IconNotes' }),
  ],
  OUTSOURCING: [
    buildStatusField([
      'Researching',
      'Available',
      'Engaged',
      'On hold',
      'Inactive',
    ]),
    buildTextField({ name: 'skills', label: 'Skills' }),
    buildTextField({ name: 'specialty', label: 'Specialty' }),
    buildTextField({
      name: 'hourlyRate',
      label: 'Hourly rate',
      icon: 'IconCurrencyEuro',
    }),
    buildSelectField({
      name: 'availability',
      label: 'Availability',
      icon: 'IconCalendarEvent',
      optionLabels: ['Available now', 'Within a month', 'Booked', 'Unknown'],
    }),
    buildTextField({ name: 'lastProject', label: 'Last project' }),
    buildTextField({ name: 'notes', label: 'Notes', icon: 'IconNotes' }),
  ],
  FUNDRAISING: [
    buildStatusField([
      'To contact',
      'Intro requested',
      'Meeting scheduled',
      'Due diligence',
      'Committed',
      'Passed',
    ]),
    buildTextField({
      name: 'investor',
      label: 'Investor',
      icon: 'IconBuildingBank',
    }),
    buildSelectField({
      name: 'round',
      label: 'Round',
      icon: 'IconCoins',
      optionLabels: ['Pre-seed', 'Seed', 'Series A', 'Series B+', 'Other'],
    }),
    buildSelectField({
      name: 'stage',
      label: 'Stage',
      icon: 'IconFlag',
      optionLabels: [
        'Research',
        'Warm intro',
        'Pitch',
        'Negotiation',
        'Closed',
      ],
    }),
    buildDateField({ name: 'lastContactedAt', label: 'Last contacted' }),
    buildDateField({ name: 'nextMeetingAt', label: 'Next meeting' }),
    buildTextField({
      name: 'amount',
      label: 'Amount',
      icon: 'IconCurrencyEuro',
    }),
    buildTextField({ name: 'notes', label: 'Notes', icon: 'IconNotes' }),
  ],
  VC_DEALFLOW: [
    buildStatusField([
      'New',
      'Screening',
      'First meeting',
      'Due diligence',
      'Investment committee',
      'Invested',
      'Passed',
    ]),
    buildSelectField({
      name: 'dealStage',
      label: 'Deal stage',
      icon: 'IconFlag',
      optionLabels: ['Pre-seed', 'Seed', 'Series A', 'Series B+', 'Other'],
    }),
    buildTextField({ name: 'sector', label: 'Sector' }),
    buildTextField({ name: 'source', label: 'Source' }),
    buildSelectField({
      name: 'priority',
      label: 'Priority',
      icon: 'IconFlag',
      optionLabels: ['Low', 'Medium', 'High'],
    }),
    buildDateField({ name: 'lastReviewedAt', label: 'Last reviewed' }),
    buildTextField({ name: 'nextStep', label: 'Next step' }),
  ],
  EMPLOYEE_ONBOARDING: [
    buildStatusField([
      'Offer accepted',
      'Before day one',
      'Week one',
      'First month',
      'Complete',
    ]),
    buildTextField({ name: 'role', label: 'Role' }),
    buildDateField({ name: 'startDate', label: 'Start date' }),
    buildTextField({ name: 'manager', label: 'Manager' }),
    buildSelectField({
      name: 'equipment',
      label: 'Equipment',
      icon: 'IconDeviceLaptop',
      optionLabels: ['Not requested', 'Requested', 'Ready', 'Delivered'],
    }),
    buildSelectField({
      name: 'training',
      label: 'Training',
      icon: 'IconBook',
      optionLabels: ['Not started', 'In progress', 'Complete'],
    }),
    buildDateField({ name: 'nextCheckInAt', label: 'Next check-in' }),
  ],
});

export const getRecordListTemplateFields = (
  templateKey: RecordListTemplateKey,
) => buildRecordListTemplateFields()[templateKey];
