// Generated by tools/native-apps/build.mjs. Edit the native app package instead.
import { msg } from '@lingui/core/macro';
import { assertUnreachable } from 'twenty-shared/utils';

import { STANDARD_ERROR_MESSAGE } from 'src/engine/core-modules/application/native-extension-host/api/engine/api/common/common-query-runners/errors/standard-error-message.constant';
import { CustomException } from 'src/engine/core-modules/application/native-extension-host/api/utils/custom-exception';

export const RecordListExceptionCode = {
  RECORD_LIST_NOT_FOUND: 'RECORD_LIST_NOT_FOUND',
  RECORD_LIST_ENTRY_NOT_FOUND: 'RECORD_LIST_ENTRY_NOT_FOUND',
  SOURCE_RECORD_NOT_FOUND: 'SOURCE_RECORD_NOT_FOUND',
  PARENT_OBJECT_NOT_FOUND: 'PARENT_OBJECT_NOT_FOUND',
  RECORD_LIST_FIELD_NOT_FOUND: 'RECORD_LIST_FIELD_NOT_FOUND',
  SYSTEM_FIELD_NOT_EDITABLE: 'SYSTEM_FIELD_NOT_EDITABLE',
  DEFAULT_VIEW_NOT_FOUND: 'DEFAULT_VIEW_NOT_FOUND',
  UNSUPPORTED_PARENT_OBJECT: 'UNSUPPORTED_PARENT_OBJECT',
  UPDATE_FAILED: 'UPDATE_FAILED',
  INTERNAL_SERVER_ERROR: 'INTERNAL_SERVER_ERROR',
} as const;

type RecordListExceptionCode =
  (typeof RecordListExceptionCode)[keyof typeof RecordListExceptionCode];

const getRecordListExceptionUserFriendlyMessage = (
  code: RecordListExceptionCode,
) => {
  switch (code) {
    case RecordListExceptionCode.RECORD_LIST_NOT_FOUND:
      return msg`List not found.`;
    case RecordListExceptionCode.RECORD_LIST_ENTRY_NOT_FOUND:
      return msg`List entry not found.`;
    case RecordListExceptionCode.SOURCE_RECORD_NOT_FOUND:
      return msg`The selected record could not be found.`;
    case RecordListExceptionCode.PARENT_OBJECT_NOT_FOUND:
      return msg`The selected object could not be found.`;
    case RecordListExceptionCode.RECORD_LIST_FIELD_NOT_FOUND:
      return msg`The selected field does not belong to this list.`;
    case RecordListExceptionCode.SYSTEM_FIELD_NOT_EDITABLE:
      return msg`This list field cannot be changed.`;
    case RecordListExceptionCode.DEFAULT_VIEW_NOT_FOUND:
      return msg`The selected view does not belong to this list.`;
    case RecordListExceptionCode.UNSUPPORTED_PARENT_OBJECT:
      return msg`Lists support people and companies.`;
    case RecordListExceptionCode.UPDATE_FAILED:
      return msg`The list could not be updated.`;
    case RecordListExceptionCode.INTERNAL_SERVER_ERROR:
      return STANDARD_ERROR_MESSAGE;
    default:
      assertUnreachable(code);
  }
};

export class RecordListException extends CustomException<RecordListExceptionCode> {
  constructor(message: string, code: RecordListExceptionCode) {
    super(message, code, {
      userFriendlyMessage: getRecordListExceptionUserFriendlyMessage(code),
    });
  }
}
