// Generated by tools/native-apps/build.mjs. Edit the native app package instead.
import { Module } from '@nestjs/common';
import { TypeOrmModule } from '@nestjs/typeorm';

import { FieldMetadataModule } from 'src/engine/core-modules/application/native-extension-host/api/engine/metadata-modules/field-metadata/field-metadata.module';
import { ObjectMetadataModule } from 'src/engine/core-modules/application/native-extension-host/api/engine/metadata-modules/object-metadata/object-metadata.module';
import { RecordListEntity } from './entities/record-list.entity';
import { RecordListResolver } from './record-list.resolver';
import { RecordListService } from './services/record-list.service';
import { provideWorkspaceScopedRepository } from 'src/engine/core-modules/application/native-extension-host/api/engine/twenty-orm/workspace-scoped-repository/provide-workspace-scoped-repository';
import { ViewFieldModule } from 'src/engine/core-modules/application/native-extension-host/api/engine/metadata-modules/view-field/view-field.module';
import { ViewEntity } from 'src/engine/core-modules/application/native-extension-host/api/engine/metadata-modules/view/entities/view.entity';
import { ActorModule } from 'src/engine/core-modules/application/native-extension-host/api/engine/core-modules/actor/actor.module';
import { ViewModule } from 'src/engine/core-modules/application/native-extension-host/api/engine/metadata-modules/view/view.module';

@Module({
  imports: [
    TypeOrmModule.forFeature([RecordListEntity, ViewEntity]),
    FieldMetadataModule,
    ObjectMetadataModule,
    ViewFieldModule,
    ActorModule,
    ViewModule,
  ],
  providers: [
    RecordListService,
    RecordListResolver,
    provideWorkspaceScopedRepository(RecordListEntity),
    provideWorkspaceScopedRepository(ViewEntity),
  ],
  exports: [RecordListService],
})
export class RecordListModule {}
