// Generated by tools/native-apps/build.mjs. Edit the native app package instead.
import { styled } from '@linaria/react';
import { t } from '@lingui/core/macro';
import { themeCssVariables } from 'twenty-ui/theme';

const StyledSection = styled.div`
  border: 1px solid ${themeCssVariables.border.color.medium};
  border-radius: ${themeCssVariables.border.radius.sm};
  display: flex;
  flex-direction: column;
  gap: ${themeCssVariables.spacing[1]};
  padding: ${themeCssVariables.spacing[3]};
`;

const StyledMuted = styled.div`
  color: ${themeCssVariables.font.color.tertiary};
`;

export const HostSampleRecordSection = ({
  sourceRecordId,
  parentObjectMetadataId,
}: {
  sourceRecordId: string;
  parentObjectMetadataId: string;
}) => (
  <StyledSection data-testid="native-host-sample-record-section">
    <span>{t`Native host sample`}</span>
    <StyledMuted>
      {t`Record page section registered for object ${parentObjectMetadataId} and record ${sourceRecordId}.`}
    </StyledMuted>
  </StyledSection>
);
