// Generated by tools/native-apps/build.mjs. Edit the native app package instead.
import { type NativeAppDefinition } from '@/app/native-extension-host/types/NativeAppDefinition';
export const NATIVE_APP_DEFINITIONS: NativeAppDefinition[] = [{
  universalIdentifier: "5f1d0c2e-9a44-4a3b-8f2f-6a1b2c3d4e5f",
  version: "1.0.0",
  routes: [{ path: "/native-host-sample", load: () => import('./5f1d0c2e-9a44-4a3b-8f2f-6a1b2c3d4e5f/frontend/HostSamplePage').then(module => ({ default: module.HostSamplePage })) }],
  navigation: [{ id: "native-host-sample", position: 200, load: () => import('./5f1d0c2e-9a44-4a3b-8f2f-6a1b2c3d4e5f/frontend/components/HostSampleNavigationItem').then(module => ({ default: module.HostSampleNavigationItem })) }],
  recordSections: [{ id: "native-host-sample-section", position: 200, objectNames: ["person","company"], load: () => import('./5f1d0c2e-9a44-4a3b-8f2f-6a1b2c3d4e5f/frontend/components/HostSampleRecordSection').then(module => ({ default: module.HostSampleRecordSection })) }],
  commands: [{ key: "NATIVE_HOST_SAMPLE", load: () => import('./5f1d0c2e-9a44-4a3b-8f2f-6a1b2c3d4e5f/frontend/HostSampleCommand').then(module => ({ default: module.HostSampleCommand })) }],
},
{
  universalIdentifier: "ac8f2b7a-15d3-47fa-a06c-2bfc6d85ec72",
  version: "1.0.0",
  routes: [{ path: "/lists/:recordListId", load: () => import('./ac8f2b7a-15d3-47fa-a06c-2bfc6d85ec72/frontend/RecordListPage').then(module => ({ default: module.RecordListPage })) }],
  navigation: [{ id: "lists", position: 10000, load: () => import('./ac8f2b7a-15d3-47fa-a06c-2bfc6d85ec72/frontend/components/RecordListsSection').then(module => ({ default: module.RecordListsSection })) }],
  recordSections: [{ id: "memberships", position: 100, objectNames: ["person","company"], load: () => import('./ac8f2b7a-15d3-47fa-a06c-2bfc6d85ec72/frontend/components/RecordListMembershipsSection').then(module => ({ default: module.RecordListMembershipsSection })) }],
  commands: [{ key: "94bb66e8-8284-4ba2-af8b-d31ecb345317", label: "Add to list", shortLabel: "Add to list", load: () => import('./ac8f2b7a-15d3-47fa-a06c-2bfc6d85ec72/frontend/AddRecordsToListCommand').then(module => ({ default: module.AddRecordsToListCommand })) },{ key: "1f9d6ca3-80f6-4d9c-a120-88ca6b778a21", label: "Remove from list", shortLabel: "Remove from list", load: () => import('./ac8f2b7a-15d3-47fa-a06c-2bfc6d85ec72/frontend/RemoveRecordsFromListCommand').then(module => ({ default: module.RemoveRecordsFromListCommand })) },{ key: "2e662e67-aed3-4e56-92d7-752cf2677981", label: "Remove from list", shortLabel: "Remove from list", load: () => import('./ac8f2b7a-15d3-47fa-a06c-2bfc6d85ec72/frontend/BulkRemoveRecordsFromListCommand').then(module => ({ default: module.BulkRemoveRecordsFromListCommand })) }],
}];
