// Generated by tools/native-apps/build.mjs. Edit the native app package instead.
import { useMutation } from '@apollo/client/react';

import { CREATE_RECORD_LIST } from '../graphql/mutations/createRecordList';
import { FIND_RECORD_LISTS } from '../graphql/queries/findRecordLists';
import { type RecordList } from '../types/RecordList';
import {
  type RecordListTemplateField,
  type RecordListTemplateKey,
} from '../constants/recordListTemplates';

export const useCreateRecordList = () => {
  const [createRecordListMutation, mutationState] = useMutation<
    { createRecordList: RecordList },
    {
      input: {
        name: string;
        icon?: string | null;
        parentObjectMetadataId: string;
        templateKey?: RecordListTemplateKey | null;
        templateFields?: RecordListTemplateField[] | null;
      };
    }
  >(CREATE_RECORD_LIST, {
    refetchQueries: [{ query: FIND_RECORD_LISTS }],
  });

  const createRecordList = async (input: {
    name: string;
    icon?: string | null;
    parentObjectMetadataId: string;
    templateKey?: RecordListTemplateKey | null;
    templateFields?: RecordListTemplateField[] | null;
  }) => {
    const result = await createRecordListMutation({ variables: { input } });

    return result.data?.createRecordList;
  };

  return { createRecordList, ...mutationState };
};
