// Generated by tools/native-apps/build.mjs. Edit the native app package instead.
import { useMutation, useQuery } from '@apollo/client/react';

import { ADD_RECORD_TO_LIST } from '../graphql/mutations/addRecordToList';
import { REMOVE_RECORD_FROM_LIST } from '../graphql/mutations/removeRecordFromList';
import { FIND_RECORD_LIST_ENTRIES } from '../graphql/queries/findRecordListEntries';
import { type RecordListEntry } from '../types/RecordList';
import { evictRecordListEntriesFromCache } from '../utils/evictRecordListEntriesFromCache';

const EMPTY_RECORD_LIST_ENTRIES: RecordListEntry[] = [];

export const useRecordListEntries = (recordListId: string) => {
  const queryVariables = { recordListId };
  const query = useQuery<
    { recordListEntries: RecordListEntry[] },
    { recordListId: string }
  >(FIND_RECORD_LIST_ENTRIES, {
    variables: queryVariables,
    skip: recordListId.length === 0,
  });
  const [addMutation, addMutationState] = useMutation<
    { addRecordToList: RecordListEntry },
    { input: { recordListId: string; sourceRecordId: string } }
  >(ADD_RECORD_TO_LIST, {
    refetchQueries: [
      { query: FIND_RECORD_LIST_ENTRIES, variables: queryVariables },
    ],
    update: (cache) => {
      evictRecordListEntriesFromCache(cache, recordListId);
    },
  });
  const [removeMutation, removeMutationState] = useMutation<
    { removeRecordFromList: RecordListEntry },
    { recordListId: string; entryId: string }
  >(REMOVE_RECORD_FROM_LIST, {
    refetchQueries: [
      { query: FIND_RECORD_LIST_ENTRIES, variables: queryVariables },
    ],
    update: (cache) => {
      evictRecordListEntriesFromCache(cache, recordListId);
    },
  });

  const addRecordToList = async (sourceRecordId: string) =>
    await addMutation({
      variables: { input: { recordListId, sourceRecordId } },
    });

  const removeRecordFromList = async (entryId: string) =>
    await removeMutation({ variables: { recordListId, entryId } });

  return {
    ...query,
    recordListEntries:
      query.data?.recordListEntries ?? EMPTY_RECORD_LIST_ENTRIES,
    addRecordToList,
    removeRecordFromList,
    isAddingRecord: addMutationState.loading,
    isRemovingRecord: removeMutationState.loading,
  };
};
