// Generated by tools/native-apps/build.mjs. Edit the native app package instead.
import { useMutation } from '@apollo/client/react';

import { FIND_RECORD_LIST_MEMBERSHIPS } from '../graphql/queries/findRecordListMemberships';
import { REMOVE_RECORDS_FROM_LIST_BY_SOURCE_RECORD_IDS } from '../graphql/mutations/removeRecordsFromListBySourceRecordIds';
import { evictRecordListEntriesFromCache } from '../utils/evictRecordListEntriesFromCache';

type RemoveRecordsFromListResult = {
  removedCount: number;
  skippedCount: number;
};

export const useRemoveRecordsFromListBySourceRecordIds = () => {
  const [removeMutation, mutationState] = useMutation<
    {
      removeRecordsFromListBySourceRecordIds: RemoveRecordsFromListResult;
    },
    { recordListId: string; sourceRecordIds: string[] }
  >(REMOVE_RECORDS_FROM_LIST_BY_SOURCE_RECORD_IDS);

  const removeRecordsFromList = async ({
    recordListId,
    sourceRecordIds,
    parentObjectMetadataId,
  }: {
    recordListId: string;
    sourceRecordIds: string[];
    parentObjectMetadataId: string;
  }) => {
    const result = await removeMutation({
      variables: { recordListId, sourceRecordIds },
      update: (cache) => {
        evictRecordListEntriesFromCache(cache, recordListId);
      },
      refetchQueries: sourceRecordIds.map((sourceRecordId) => ({
        query: FIND_RECORD_LIST_MEMBERSHIPS,
        variables: { sourceRecordId, parentObjectMetadataId },
      })),
      awaitRefetchQueries: true,
    });

    return result.data?.removeRecordsFromListBySourceRecordIds;
  };

  return { removeRecordsFromList, ...mutationState };
};
