// Generated by tools/native-apps/build.mjs. Edit the native app package instead.
import { useQuery } from '@apollo/client/react';

import { FIND_RECORD_LIST } from '../graphql/queries/findRecordList';
import { type RecordList } from '../types/RecordList';

export const useRecordList = (recordListId: string) => {
  const query = useQuery<{ recordList: RecordList }, { id: string }>(
    FIND_RECORD_LIST,
    {
      variables: { id: recordListId },
      skip: recordListId.length === 0,
    },
  );

  return { ...query, recordList: query.data?.recordList };
};
