// Generated by tools/native-apps/build.mjs. Edit the native app package instead.
import { gql } from '@apollo/client';

export const RECORD_LIST_FRAGMENT = gql`
  fragment RecordListFields on RecordList {
    id
    name
    icon
    position
    parentObjectMetadataId
    entryObjectMetadataId
    defaultViewId
    createdAt
    updatedAt
  }
`;
